(() => {
  'use strict';
  const KEY = 'hugcode-workboard-v1';
  const STATUSES = [
    { id: 'todo', label: 'รอดำเนินการ', color: '#9caabd' },
    { id: 'doing', label: 'กำลังดำเนินการ', color: '#5685ee' },
    { id: 'review', label: 'รอตรวจสอบ', color: '#a17be7' },
    { id: 'done', label: 'เสร็จแล้ว', color: '#43b487' }
  ];
  const DEFAULT_OPTIONS = { assignees: ['นภัส (Napas)', 'พิมพ์ชนก (Pim)', 'ธนกร (Ton)', 'วรินทร์ (Win)'], assigners: ['อรทัย (Aor)', 'ธนกร (Ton)', 'หัวหน้าทีม'], modules: ['Dashboard', 'Mobile App', 'API', 'Design System', 'Infrastructure'] };
  const isoDay = n => { const d = new Date(); d.setDate(d.getDate() + n); return d.toISOString().slice(0, 10); };
  const assigned = (day, hour = '09:00') => `${day}T${hour}`;
  const seed = { options: structuredClone(DEFAULT_OPTIONS), tasks: [
    { id:'t1',title:'ออกแบบหน้า Dashboard ภาพรวม',module:'Dashboard',description:'สรุปตัวชี้วัดสำคัญและปรับลำดับข้อมูลให้ทีมเห็นภาพรวมได้ในหน้าเดียว',tags:['UI','Analytics'],assignee:'พิมพ์ชนก (Pim)',assigner:'อรทัย (Aor)',priority:'high',assignedAt:assigned(isoDay(-3),'10:30'),dueDate:isoDay(2),status:'doing',comments:[{author:'อรทัย (Aor)',text:'ฝากดู spacing บนหน้าจอแท็บเล็ตด้วยนะ',createdAt:assigned(isoDay(-2),'14:10')}]},
    { id:'t2',title:'วางโครงสร้างฐานข้อมูลสมาชิก',module:'API',description:'กำหนด schema สำหรับโปรไฟล์และสิทธิ์การใช้งาน รองรับการขยายในอนาคต',tags:['PostgreSQL','Schema'],assignee:'ธนกร (Ton)',assigner:'หัวหน้าทีม',priority:'medium',assignedAt:assigned(isoDay(-2),'09:15'),dueDate:isoDay(4),status:'todo',comments:[]},
    { id:'t3',title:'ปรับปรุงระบบเข้าสู่ระบบ',module:'Mobile App',description:'เพิ่ม validation และจัดการข้อผิดพลาดจาก API ให้ข้อความเข้าใจง่าย',tags:['Auth','UX'],assignee:'นภัส (Napas)',assigner:'อรทัย (Aor)',priority:'high',assignedAt:assigned(isoDay(-5),'13:00'),dueDate:isoDay(1),status:'review',comments:[{author:'วรินทร์ (Win)',text:'ทดสอบบน Android แล้ว ผ่านเรียบร้อย',createdAt:assigned(isoDay(-1),'16:20')}]},
    { id:'t4',title:'สร้างชุดปุ่มมาตรฐาน',module:'Design System',description:'เตรียม variants, states และเอกสารการใช้งานสำหรับทีม frontend',tags:['Component','Docs'],assignee:'พิมพ์ชนก (Pim)',assigner:'หัวหน้าทีม',priority:'low',assignedAt:assigned(isoDay(-7),'11:00'),dueDate:isoDay(-1),status:'done',comments:[]},
    { id:'t5',title:'ตั้งค่า staging environment',module:'Infrastructure',description:'จัดเตรียม environment สำหรับทดสอบก่อนปล่อยเวอร์ชันจริง',tags:['Deploy','DevOps'],assignee:'วรินทร์ (Win)',assigner:'ธนกร (Ton)',priority:'medium',assignedAt:assigned(isoDay(-1),'15:45'),dueDate:isoDay(5),status:'doing',comments:[]},
    { id:'t6',title:'ตรวจสอบ flow สมัครสมาชิก',module:'Mobile App',description:'ทวนขั้นตอนสมัครสมาชิกให้ลื่นไหลและรองรับผู้ใช้ใหม่',tags:['Onboarding','QA'],assignee:'นภัส (Napas)',assigner:'อรทัย (Aor)',priority:'low',assignedAt:assigned(isoDay(-1),'10:20'),dueDate:isoDay(6),status:'todo',comments:[]},
    { id:'t7',title:'เพิ่ม endpoint รายงานกิจกรรม',module:'API',description:'ส่งข้อมูลกิจกรรมรายวันพร้อม pagination ให้ dashboard',tags:['REST','Reports'],assignee:'ธนกร (Ton)',assigner:'หัวหน้าทีม',priority:'medium',assignedAt:assigned(isoDay(-4),'08:50'),dueDate:isoDay(3),status:'review',comments:[]}
  ]};
  const $ = id => document.getElementById(id);
  let state = loadLocal(), client = null, channel = null, user = null, localMode = true, toastTimer;
  function loadLocal(){ try { const v = JSON.parse(localStorage.getItem(KEY)); if(v?.tasks && v?.options) return v; } catch(e){} return structuredClone(seed); }
  function stamp(){ return new Date().toLocaleTimeString('th-TH',{hour:'2-digit',minute:'2-digit'}); }
  function saveLocal(){ localStorage.setItem(KEY,JSON.stringify(state)); $('lastSync').textContent=stamp(); }
  function notify(message){ const el=$('toast');el.textContent=message;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),2500); }
  function setConnection(text, cls=''){ const el=$('connection');el.className=`connection ${cls}`;el.querySelector('span').textContent=text; }
  function escapeHtml(s=''){ return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])); }
  function initials(s=''){return s.split(/[ (]/).filter(Boolean).slice(0,2).map(x=>x[0]).join('').toUpperCase()||'HC';}
  function prettyDate(s){if(!s)return 'ไม่ระบุ';const d=new Date(s.length===10?`${s}T00:00:00`:s);return d.toLocaleDateString('th-TH',{day:'numeric',month:'short'});}
  function fillSelect(el,items,placeholder='เลือก'){const old=el.value;el.innerHTML=`<option value="">${placeholder}</option>`+items.map(x=>`<option value="${escapeHtml(x)}">${escapeHtml(x)}</option>`).join('');if(items.includes(old))el.value=old;}
  function populateOptions(){const o=state.options;fillSelect($('assigneeFilter'),o.assignees,'ผู้รับผิดชอบทั้งหมด');fillSelect($('taskAssignee'),o.assignees,'เลือกผู้รับผิดชอบ');fillSelect($('taskAssigner'),o.assigners,'เลือกผู้มอบหมาย');fillSelect($('taskModule'),o.modules,'เลือกโมดูล');fillSelect($('taskStatus'),state.statuses||STATUSES.map(s=>s.id),'เลือกสถานะ');$('taskStatus').querySelectorAll('option').forEach(opt=>{const s=(state.statuses||STATUSES.map(s=>s.id)).find(x=>x.id===opt.value);if(s)opt.textContent=s.label;});}
  function currentStatuses(){return state.statuses||STATUSES;}
  function isFiltered(){return !!($('searchInput').value.trim()||$('assigneeFilter').value||$('dateFilter').value||$('dateFrom').value||$('dateTo').value);}
  function filteredTasks(){let tasks=[...state.tasks];const q=$('searchInput').value.trim().toLowerCase(),assignee=$('assigneeFilter').value,kind=$('dateFilter').value,from=$('dateFrom').value,to=$('dateTo').value;if(q)tasks=tasks.filter(t=>[t.title,t.module,t.description,...(t.tags||[])].join(' ').toLowerCase().includes(q));if(assignee)tasks=tasks.filter(t=>t.assignee===assignee);if(from||to){tasks=tasks.filter(t=>{const d=kind==='due'?t.dueDate:t.assignedAt?.slice(0,10);return d&&(!from||d>=from)&&(!to||d<=to);});}return tasks;}
  function render(){if(state.statuses){state.tasks.forEach(t=>{if(!state.statuses.some(s=>s.id===t.status))t.status=state.statuses[0]?.id;});}populateOptions();const tasks=filteredTasks();$('totalCount').textContent=state.tasks.length;$('activeCount').textContent=state.tasks.filter(t=>t.status==='doing').length;const board=$('board');board.innerHTML='';for(const status of currentStatuses()){const items=tasks.filter(t=>t.status===status.id);const column=document.createElement('div');column.className='board-column';column.innerHTML=`<div class="column-head"><i class="column-dot" style="background:${status.color||'#9caabd'}"></i><span class="column-title">${escapeHtml(status.label)}</span><span class="column-count">${items.length}</span></div><div class="column-list" data-status="${escapeHtml(status.id)}" aria-label="${escapeHtml(status.label)}"></div>`;const list=column.querySelector('.column-list');if(!items.length)list.innerHTML='<div class="empty-state">ไม่มีงานในสถานะนี้</div>';for(const task of items)list.append(makeCard(task));board.append(column);}wireDnD();}
  function makeCard(t){const card=document.createElement('article');card.className='task-card';card.draggable=true;card.dataset.id=t.id;const priority={high:['สูง','high'],medium:['ปานกลาง','medium'],low:['ต่ำ','low']}[t.priority]||['ปานกลาง','medium'];const due=t.dueDate?new Date(`${t.dueDate}T23:59:59`):null;const overdue=due&&due<new Date()&&t.status!=='done';card.innerHTML=`<div class="task-top"><span class="module-label">${escapeHtml(t.module||'ทั่วไป')}</span><div class="menu-wrap"><button class="task-menu-btn" aria-label="เมนูงาน ${escapeHtml(t.title)}" title="เมนูงาน">⋯</button><div class="task-menu" hidden><button data-action="edit">แก้ไขรายละเอียด</button><button data-action="status">เปลี่ยนสถานะ</button><button data-action="delete" class="delete-option">ลบงาน</button></div></div></div><h3 class="task-title">${escapeHtml(t.title)}</h3><p class="task-desc">${escapeHtml(t.description||'ไม่มีรายละเอียด')}</p><div class="tags">${(t.tags||[]).map(x=>`<span class="tag">${escapeHtml(x)}</span>`).join('')}</div><div class="task-meta"><span class="person"><span class="person-avatar">${escapeHtml(initials(t.assignee))}</span><span>${escapeHtml(t.assignee||'ไม่ระบุ')}</span></span><span class="priority ${priority[1]}">${priority[0]}</span></div><div class="task-dates"><span>ส่ง ${escapeHtml(prettyDate(t.dueDate))}</span><span class="${overdue?'overdue':''}">${t.comments?.length?`☰ ${t.comments.length}`:escapeHtml(prettyDate(t.assignedAt||''))}</span></div>`;
    card.addEventListener('click',e=>{if(e.target.closest('.task-menu-btn')||e.target.closest('.task-menu'))return;openTask(t.id);});const menu=card.querySelector('.task-menu');card.querySelector('.task-menu-btn').addEventListener('click',e=>{e.stopPropagation();document.querySelectorAll('.task-menu').forEach(m=>{if(m!==menu)m.hidden=true;});menu.hidden=!menu.hidden;});menu.addEventListener('click',e=>{const action=e.target.dataset.action;if(!action)return;e.stopPropagation();menu.hidden=true;if(action==='edit')openTask(t.id);if(action==='delete')deleteTask(t.id);if(action==='status')chooseStatus(t);});return card;}
  function wireDnD(){document.querySelectorAll('.task-card').forEach(card=>{card.addEventListener('dragstart',e=>{e.dataTransfer.setData('text/plain',card.dataset.id);e.dataTransfer.effectAllowed='move';card.classList.add('dragging');});card.addEventListener('dragend',()=>card.classList.remove('dragging'));});document.querySelectorAll('.column-list').forEach(list=>{list.addEventListener('dragover',e=>{e.preventDefault();list.classList.add('drag-over');});list.addEventListener('dragleave',()=>list.classList.remove('drag-over'));list.addEventListener('drop',e=>{e.preventDefault();list.classList.remove('drag-over');const task=state.tasks.find(t=>t.id===e.dataTransfer.getData('text/plain'));if(task&&task.status!==list.dataset.status){task.status=list.dataset.status;persist();notify('ย้ายงานแล้ว');}});});}
  function persist(){saveLocal();render();if(client&&!localMode)syncRemote();}
  function getPayload(){return {tasks:state.tasks,options:state.options,statuses:state.statuses||null,updated_at:new Date().toISOString(),updated_by:user?.id||null};}
  async function syncRemote(){if(!client||localMode)return;setConnection('กำลังซิงก์','syncing');const {error}=await client.from('workboard_state').upsert({id:1,...getPayload()},{onConflict:'id'});if(error){setConnection('ซิงก์ไม่สำเร็จ','offline');$('errorBanner').hidden=false;$('errorBanner').textContent=`ซิงก์ข้อมูลไม่สำเร็จ: ${error.message} · ข้อมูลในเครื่องยังคงอยู่`;return;}$('errorBanner').hidden=true;setConnection('ซิงก์แล้ว');$('lastSync').textContent=stamp();}
  async function loadRemote(){const {data,error}=await client.from('workboard_state').select('*').eq('id',1).maybeSingle();if(error)throw error;if(data){if(data.tasks&&data.options)state={tasks:data.tasks,options:data.options,statuses:data.statuses||undefined};saveLocal();render();}else{state=structuredClone(seed);saveLocal();await syncRemote();}channel=client.channel('hugcode-workboard').on('postgres_changes',{event:'*',schema:'public',table:'workboard_state'},payload=>{const row=payload.new;if(row?.tasks&&row?.options){state={tasks:row.tasks,options:row.options,statuses:row.statuses||undefined};saveLocal();render();notify('มีข้อมูลบอร์ดอัปเดตจากทีม');}}).subscribe(s=>{if(s==='SUBSCRIBED')setConnection('ออนไลน์');else if(s==='CHANNEL_ERROR'||s==='TIMED_OUT')setConnection('ออฟไลน์','offline');});}
  function openTask(id){const t=state.tasks.find(x=>x.id===id);$('formError').textContent='';$('taskId').value=t?.id||'';$('taskDialogTitle').textContent=t?'แก้ไขงาน':'เพิ่มงานใหม่';$('taskTitle').value=t?.title||'';$('taskModule').value=t?.module||'';$('taskStatus').value=t?.status||'todo';$('taskDescription').value=t?.description||'';$('taskTags').value=(t?.tags||[]).join(', ');$('taskPriority').value=t?.priority||'medium';$('taskAssignee').value=t?.assignee||'';$('taskAssigner').value=t?.assigner||'';$('taskAssignedAt').value=t?.assignedAt||new Date().toISOString().slice(0,16);$('taskDue').value=t?.dueDate||'';$('deleteTaskBtn').hidden=!t;$('commentsSection').hidden=!t;renderComments(t);$('taskDialog').showModal();$('taskTitle').focus();}
  function renderComments(t){const list=$('commentsList');list.innerHTML='';(t?.comments||[]).forEach(c=>{const el=document.createElement('div');el.className='comment';el.innerHTML=`<b>${escapeHtml(c.author||'ทีม Hugcode')}</b><time>${escapeHtml(prettyDate(c.createdAt))}</time><p>${escapeHtml(c.text)}</p>`;list.append(el);});$('commentCount').textContent=t?.comments?.length||0;}
  function saveTask(e){e.preventDefault();const title=$('taskTitle').value.trim();if(!title){$('formError').textContent='กรุณากรอกชื่องาน';return;}if(!$('taskAssignee').value||!$('taskAssigner').value||!$('taskModule').value){$('formError').textContent='กรุณาเลือกโมดูล ผู้รับผิดชอบ และผู้มอบหมาย';return;}const id=$('taskId').value;const old=state.tasks.find(t=>t.id===id);const task={id:id||crypto.randomUUID(),title,module:$('taskModule').value,status:$('taskStatus').value,description:$('taskDescription').value.trim(),tags:$('taskTags').value.split(',').map(x=>x.trim()).filter(Boolean),priority:$('taskPriority').value,assignee:$('taskAssignee').value,assigner:$('taskAssigner').value,assignedAt:$('taskAssignedAt').value,dueDate:$('taskDue').value,comments:old?.comments||[]};if(old)state.tasks=state.tasks.map(t=>t.id===id?task:t);else state.tasks.unshift(task);$('taskDialog').close();persist();notify(old?'บันทึกการแก้ไขแล้ว':'เพิ่มงานแล้ว');}
  function deleteTask(id){const t=state.tasks.find(x=>x.id===id);if(!t)return;if(!confirm(`ลบงาน “${t.title}” ใช่หรือไม่?`))return;state.tasks=state.tasks.filter(x=>x.id!==id);$('taskDialog').close();persist();notify('ลบงานแล้ว');}
  function chooseStatus(t){const choices=currentStatuses().map((s,i)=>`${i+1}. ${s.label}`).join('\n');const answer=prompt(`เลือกสถานะใหม่ของงาน “${t.title}”\n${choices}\nกรอกชื่อสถานะหรือหมายเลข:`);if(answer===null)return;const n=Number(answer),s=currentStatuses()[n-1]||currentStatuses().find(x=>x.label.toLowerCase()===answer.trim().toLowerCase()||x.id===answer.trim());if(!s){notify('ไม่พบสถานะที่เลือก');return;}t.status=s.id;persist();notify('เปลี่ยนสถานะแล้ว');}
  function addComment(){const id=$('taskId').value,t=state.tasks.find(x=>x.id===id),text=$('commentInput').value.trim();if(!t||!text)return;t.comments=t.comments||[];t.comments.push({author:user?.email||'ทีม Hugcode',text,createdAt:new Date().toISOString()});$('commentInput').value='';renderComments(t);persist();}
  function exportExcel(){const tasks=filteredTasks();const rows=[['ชื่องาน','โมดูล','รายละเอียด','แท็ก','ผู้รับผิดชอบ','ผู้มอบหมาย','ความสำคัญ','วันที่มอบหมาย','กำหนดส่ง','สถานะ','ความคิดเห็น'],...tasks.map(t=>[t.title,t.module,t.description,(t.tags||[]).join(', '),t.assignee,t.assigner,{low:'ต่ำ',medium:'ปานกลาง',high:'สูง'}[t.priority]||t.priority,t.assignedAt,t.dueDate,currentStatuses().find(s=>s.id===t.status)?.label||t.status,(t.comments||[]).map(c=>`${c.author}: ${c.text}`).join(' | ')])];const csv='\ufeff'+rows.map(r=>r.map(v=>'"'+String(v??'').replace(/"/g,'""')+'"').join(',')).join('\r\n');const blob=new Blob([csv],{type:'application/vnd.ms-excel;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`hugcode-workboard-${isoDay(0)}.xls`;a.click();URL.revokeObjectURL(a.href);notify('ส่งออกไฟล์ Excel แล้ว');}
  function renderSettings(){const groups=[['assignees','ผู้รับผิดชอบ'],['assigners','ผู้มอบหมาย'],['modules','โมดูล'],['statuses','สถานะ']];$('settingsLists').innerHTML='';groups.forEach(([key,label])=>{const entries=key==='statuses'?currentStatuses().map(s=>({value:s.label,id:s.id})):state.options[key].map(s=>({value:s}));const box=document.createElement('section');box.className='setting-group';box.innerHTML=`<h3>${label}</h3><div class="setting-items"></div><div class="setting-add"><input aria-label="เพิ่ม${label}" placeholder="เพิ่ม${label}ใหม่"><button type="button">เพิ่ม</button></div>`;const list=box.querySelector('.setting-items');entries.forEach((entry,index)=>{const row=document.createElement('div');row.className='setting-item';row.innerHTML=`<input aria-label="${label} ${escapeHtml(entry.value)}" value="${escapeHtml(entry.value)}"><button type="button" title="บันทึก">✓</button><button type="button" title="ลบ" aria-label="ลบ ${escapeHtml(entry.value)}">×</button>`;const input=row.querySelector('input'),[save,del]=row.querySelectorAll('button');save.addEventListener('click',()=>{const value=input.value.trim();if(!value){notify('รายการต้องไม่ว่าง');return;}if(key==='statuses'){const old=currentStatuses()[index];old.label=value;}else state.options[key][index]=value;persist();renderSettings();});del.addEventListener('click',()=>{if(!confirm(`ลบรายการ “${entry.value}” ใช่หรือไม่?`))return;if(key==='statuses'){if(currentStatuses().length<=1){notify('ต้องมีสถานะอย่างน้อยหนึ่งรายการ');return;}state.statuses=currentStatuses().filter((_,i)=>i!==index);}else state.options[key].splice(index,1);persist();renderSettings();});list.append(row);});box.querySelector('.setting-add button').addEventListener('click',()=>{const input=box.querySelector('.setting-add input'),value=input.value.trim();if(!value)return;if(key==='statuses'){state.statuses=currentStatuses();state.statuses.push({id:`status_${crypto.randomUUID().slice(0,8)}`,label:value,color:'#7e9bd1'});}else state.options[key].push(value);persist();renderSettings();});$('settingsLists').append(box);});}
  function setupEvents(){ $('addTaskBtn').addEventListener('click',()=>openTask());$('taskForm').addEventListener('submit',saveTask);document.querySelectorAll('.close-dialog').forEach(b=>b.addEventListener('click',()=>$('taskDialog').close()));$('deleteTaskBtn').addEventListener('click',()=>deleteTask($('taskId').value));$('addCommentBtn').addEventListener('click',addComment);$('commentInput').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();addComment();}});$('searchInput').addEventListener('input',render);$('assigneeFilter').addEventListener('change',render);['dateFilter','dateFrom','dateTo'].forEach(id=>$(id).addEventListener('change',render));$('clearFilters').addEventListener('click',()=>{['searchInput','assigneeFilter','dateFilter','dateFrom','dateTo'].forEach(id=>$(id).value='');render();});$('exportBtn').addEventListener('click',exportExcel);$('settingsBtn').addEventListener('click',()=>{renderSettings();$('settingsDialog').showModal();});document.querySelectorAll('.close-settings').forEach(b=>b.addEventListener('click',()=>$('settingsDialog').close()));$('logoutBtn').addEventListener('click',async()=>{if(client&&user)await client.auth.signOut();user=null;renderAuth();});$('authForm').addEventListener('submit',async e=>{e.preventDefault();$('authError').textContent='';if(!client){$('authError').textContent='ยังไม่ได้ตั้งค่า Supabase';return;}const {error}=await client.auth.signInWithPassword({email:$('email').value,password:$('password').value});if(error)$('authError').textContent=`เข้าสู่ระบบไม่สำเร็จ: ${error.message}`;});document.addEventListener('click',e=>{if(!e.target.closest('.menu-wrap'))document.querySelectorAll('.task-menu').forEach(m=>m.hidden=true);});}
  function renderAuth(){const needsAuth=client&&!!window.HUGCODE_SUPABASE?.requireAuth;$('authScreen').hidden=!(needsAuth&&!user);$('boardScreen').hidden=needsAuth&&!user;if(!$('boardScreen').hidden)render();}
  async function init(){setupEvents();$('todayLabel').textContent=new Date().toLocaleDateString('th-TH',{weekday:'long',day:'numeric',month:'long'});const cfg=window.HUGCODE_SUPABASE||{};if(cfg.url&&cfg.anonKey&&window.supabase?.createClient){try{client=window.supabase.createClient(cfg.url,cfg.anonKey);const auth=await client.auth.getSession();user=auth.data.session?.user||null;client.auth.onAuthStateChange((_event,session)=>{user=session?.user||null;renderAuth();});if(cfg.requireAuth&&!user){renderAuth();return;}localMode=false;$('setupNotice').hidden=true;setConnection('เชื่อมต่อ Supabase','syncing');await loadRemote();renderAuth();}catch(e){console.error(e);localMode=true;$('setupNotice').hidden=false;setConnection('ทำงานในเครื่อง','offline');$('errorBanner').hidden=false;$('errorBanner').textContent=`เชื่อมต่อ Supabase ไม่สำเร็จ: ${e.message} · กำลังใช้ข้อมูลในเครื่อง`;renderAuth();}}else{$('setupNotice').hidden=false;setConnection('ทำงานในเครื่อง','offline');renderAuth();}}
  init();
})();

